import { Poppins, Dancing_Script } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/root/layout/navbar/Navbar";
import "leaflet/dist/leaflet.css";
import Footer from "@/components/root/layout/footer/Footer";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100", // thin
    "200", // extra-light
    "300", // light
    "400", // normal
    "500", // medium
    "600", // semi-bold
    "700", // bold
    "800", // extra-bold
    "900", // black
  ],
  variable: "--font-poppins",
});

export const hnd = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-hnd",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${hnd.variable}`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
